# Generated by Django 5.0.1 on 2024-02-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingsheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='week_series',
        ),
    ]
