# Generated by Django 5.0.1 on 2024-05-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='nivel_type',
            field=models.CharField(choices=[('Avançado', 'AVC'), ('Intermediário', 'INT'), ('Iniciante', 'INC')], max_length=13),
        ),
    ]
